version: '3'
services:
  python3.5:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: 3.5
  python3.6:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: 3.6
  python3.7:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: 3.7
  python3.8:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: 3.8
  python3.9:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: 3.9
  python3.10:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: 3.10
  python3.11:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: 3.11
